# The URL the site will be built for
base_url = "https://owasp-noir.github.io/noir/"
title = "OWASP Noir"
theme = "goyo"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[languages.ko]
title = "OWASP Noir"
generate_feeds = true
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo_text = "OWASP Noir"
logo_image_path = "images/logo.png"
logo_image_padding = "14px"
footer_html = "<div style='display: flex; align-items: center; justify-content: center; gap: 16px; flex-wrap: wrap;'><a href='https://owasp.org' target='_blank' rel='noopener noreferrer' style='display: inline-flex; align-items: center;'><img src='/images/owasp.png' alt='OWASP' style='height: 24px' /></a><span style='opacity: 0.6;'>•</span><span>Powered by <a href='https://www.getzola.org' class='font-medium text-base-content/70 hover:text-base-content transition-colors duration-200'>Zola</a> and <a href='https://github.com/hahwul/goyo' class='font-medium text-base-content/70 hover:text-base-content transition-colors duration-200'>Goyo</a></span></div>"
default_thumbnail = "images/bbb.jpg"
default_colorset = "dark"
brightness = "darker"
sidebar_expand_depth = 0

lang_aliases = { en = "English", ko = "한국어" }

nav = [
    { name = "Documents", url = "/noir/get_started/overview", type = "url", icon = "fa-solid fa-book" },
    { name = "GitHub", url = "https://github.com/owasp-noir/noir", type = "url", icon = "fa-brands fa-github" },
    { name = "OWASP", type = "dropdown", icon = "fa-solid fa-globe", members = [
        { name = "OWASP Project", url = "https://owasp.org/www-project-noir/", type = "url" , icon = "fa-solid fa-flag"},
        { name = "OWASP Nest", url = "https://nest.owasp.dev/projects/noir", type = "url" , icon = "fa-solid fa-igloo"},
    ] },
]

nav_ko = [
    { name = "문서", url = "/ko/noir/get_started/overview", type = "url", icon = "fa-solid fa-book" },
    { name = "GitHub", url = "https://github.com/owasp-noir/noir", type = "url", icon = "fa-brands fa-github" },
    { name = "OWASP", type = "dropdown", icon = "fa-solid fa-globe", members = [
        { name = "OWASP Project", url = "https://owasp.org/www-project-noir/", type = "url" , icon = "fa-solid fa-flag"},
        { name = "OWASP Nest", url = "https://nest.owasp.dev/projects/noir", type = "url" , icon = "fa-solid fa-igloo"},
    ] },
]
